require('nclosure').nclosure({additionalDeps:['deps.js']});
expect = require('expect.js');

goog.require('banksean.Mt19937');

describe('banksean.Mt19937',function(){
  var mt19937 = new banksean.Mt19937();

  // Parameters given in this test code are generated by source at /src/sandbox/mt19937/mt19937ar.c
  // $ clang mt19937.c
  // $ ./a.out

  it('should return proper int32 results for given seed 1000',function(){
    mt19937.srand(1000);
    expect(mt19937.getInt32()).to.be(2807145907);
    expect(mt19937.getInt32()).to.be(882709079);
    expect(mt19937.getInt32()).to.be(493951047);
    expect(mt19937.getInt32()).to.be(2621574848);
    expect(mt19937.getInt32()).to.be(4081433851);
    expect(mt19937.getInt32()).to.be(44058974);
    expect(mt19937.getInt32()).to.be(2070996316);
    expect(mt19937.getInt32()).to.be(1549632257);
    expect(mt19937.getInt32()).to.be(3747249597);
    expect(mt19937.getInt32()).to.be(3650674304);
  });

  it('should return proper rate results for given seed 1001',function(){
    mt19937.srand(1001);
    expect(mt19937.getRate()).to.be(0.3062321797478944);
    expect(mt19937.getRate()).to.be(0.3795287332031876);
    expect(mt19937.getRate()).to.be(0.26506356825120747);
    expect(mt19937.getRate()).to.be(0.5514183710329235);
    expect(mt19937.getRate()).to.be(0.19606006471440196);
    expect(mt19937.getRate()).to.be(0.22768407384864986);
    expect(mt19937.getRate()).to.be(0.4305214760825038);
    expect(mt19937.getRate()).to.be(0.44003438390791416);
    expect(mt19937.getRate()).to.be(0.023113552015274763);
  });
});
